import React from 'react'

const Privacy = () => {
    return (
        <div className="container mx-auto px-4 py-8 max-w-4xl">
            <h1 className="text-4xl font-bold mb-6">Privacy Policy</h1>
            <p className="text-gray-600 mb-4">Last updated: April 04, 2025</p>
            <p className="text-gray-700 mb-6">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>

            <h2 className="text-3xl font-semibold mb-4">Interpretation and Definitions</h2>
            <h3 className="text-2xl font-semibold mb-3">Interpretation</h3>
            <p className="text-gray-700 mb-6">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

            <h3 className="text-2xl font-semibold mb-3">Definitions</h3>
            <p className="text-gray-700 mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-4 mb-8">
                <li><p className="text-gray-700"><span className="font-semibold">Account</span> means a unique account created for You to access our Service or parts of our Service.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">Affiliate</span> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Exotic Mobiles, No,1 2323.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">Country</span> refers to: Sri Lanka</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">Personal Data</span> is any information that relates to an identified or identifiable individual.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">Service</span> refers to the Website.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">Website</span> refers to Exotic Mobiles, accessible from <a href="exoticmobiles.lk" rel="external nofollow noopener" target="_blank" className="text-blue-600 hover:text-blue-800">exoticmobiles.lk</a></p></li>
                <li><p className="text-gray-700"><span className="font-semibold">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p></li>
            </ul>

            <h2 className="text-3xl font-semibold mb-4">Collecting and Using Your Personal Data</h2>
            <h3 className="text-2xl font-semibold mb-3">Types of Data Collected</h3>
            <h4 className="text-xl font-semibold mb-3">Personal Data</h4>
            <p className="text-gray-700 mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc pl-6 space-y-2 mb-8">
                <li><p className="text-gray-700">Email address</p></li>
                <li><p className="text-gray-700">First name and last name</p></li>
                <li><p className="text-gray-700">Phone number</p></li>
                <li><p className="text-gray-700">Address, State, Province, ZIP/Postal code, City</p></li>
                <li><p className="text-gray-700">Usage Data</p></li>
            </ul>

            <h4 className="text-xl font-semibold mb-3">Usage Data</h4>
            <div className="space-y-4 mb-8">
                <p className="text-gray-700">Usage Data is collected automatically when using the Service.</p>
                <p className="text-gray-700">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <p className="text-gray-700">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                <p className="text-gray-700">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            </div>

            <h4 className="text-xl font-semibold mb-3">Tracking Technologies and Cookies</h4>
            <p className="text-gray-700 mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
            <ul className="list-disc pl-6 space-y-4 mb-6">
                <li className="text-gray-700"><span className="font-semibold">Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                <li className="text-gray-700"><span className="font-semibold">Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
            </ul>

            <p className="text-gray-700 mb-6">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on <a href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies" target="_blank" className="text-blue-600 hover:text-blue-800">TermsFeed website</a> article.</p>

            <p className="text-gray-700 mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
            <ul className="space-y-6 mb-8">
                <li>
                    <p className="font-semibold">Necessary / Essential Cookies</p>
                    <p className="text-gray-700">Type: Session Cookies</p>
                    <p className="text-gray-700">Administered by: Us</p>
                    <p className="text-gray-700">Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                </li>
                <li>
                    <p className="font-semibold">Cookies Policy / Notice Acceptance Cookies</p>
                    <p className="text-gray-700">Type: Persistent Cookies</p>
                    <p className="text-gray-700">Administered by: Us</p>
                    <p className="text-gray-700">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                </li>
                <li>
                    <p className="font-semibold">Functionality Cookies</p>
                    <p className="text-gray-700">Type: Persistent Cookies</p>
                    <p className="text-gray-700">Administered by: Us</p>
                    <p className="text-gray-700">Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                </li>
            </ul>

            <h3 className="text-2xl font-semibold mb-3">Use of Your Personal Data</h3>
            <p className="text-gray-700 mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-4 mb-8">
                <li><p className="text-gray-700"><span className="font-semibold">To provide and maintain our Service</span>, including to monitor the usage of our Service.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">To manage Your Account:</span> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">For the performance of a contract:</span> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">To contact You:</span> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">To provide You</span> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p></li>
                <li><p className="text-gray-700"><span className="font-semibold">To manage Your requests:</span> To attend and manage Your requests to Us.</p></li>
            </ul>

            <h3 className="text-2xl font-semibold mb-3">Security of Your Personal Data</h3>
            <p className="text-gray-700 mb-8">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

            <h2 className="text-3xl font-semibold mb-4">Contact Us</h2>
            <p className="text-gray-700 mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul className="list-disc pl-6 space-y-2 mb-8">
                <li><p className="text-gray-700">By email: ABS@gmail.com</p></li>
                <li><p className="text-gray-700">By visiting this page on our website: <a href="exoticmobiles.lk/Contact" rel="external nofollow noopener" target="_blank" className="text-blue-600 hover:text-blue-800">exoticmobiles.lk/contact</a></p></li>
            </ul>
        </div>
    )
}

export default Privacy